= Antora Maven Content Source Extension

This extension allows Antora to retrieve content from maven coordinates in addition to git repositories.
If parts of the documentation are generated or post-processed it's usually more convenient to package it up and publish the docs to a maven repository instead of making the build commit generated files into a git repo.
Also it's probably more common for Java hackers to refer to published artifacts than to git repos.

WARNING: The extension expects artifacts to be versioned according to https://www.npmjs.com/package/semver[SemVer]

== Usage

Publish an artifact (`zip`, `jar`, and `tgz` supported) to a maven repository.
Make sure the content adheres to the antora folder structure.

Add the extension to the playbook and make sure it's installed:
[source,yaml]
....
antora:
  extensions:
    - require: "@kiwigrid/antora-maven-content"
      repositories:
        - baseUrl: maven-central      # required
          fetchOptions:               # optional
            headers:
              "Authorization": "Basic <base64 encoded user:password>"
      sources:
        - groupId: "com.example"      # required
          artifactId: "antora-module" # required
          version: "1.x.x"            # defaults to '*'
          limit: 3                    # defaults to 1
          limitBy: minor              # defaults to 'major', one of 'major', 'minor', 'patch', 'any'
          includeSnapshots: true      # defaults to false, true has no effect if includePrerelease is false as SNAPSHOTS are SemVer pre releases
          includePrerelease: true     # defaults to true
          classifier: ""              # defaults to 'docs'
          extension: "tgz"            # defaults to 'zip'
          startPath: ~                # defaults to null
          startPaths: "docs/*"        # defaults to null
....

With above example configuration the extension is going to download all available versions for `com.example:antora-module` and picks the 3 highest version which:

* match the https://www.npmjs.com/package/semver#user-content-ranges[SemVer Range] `1.x.x`
* do not equal a higher version when reduced to the minor version
* for example:
+
|===
| Available Versions | Picked Versions

| 0.9.0 | 1.0.2
| 0.9.1 | 1.1.0
| 0.9.2 | 1.2.1
| 1.0.0 |
| 1.0.1 |
| 1.0.2 |
| 1.1.0 |
| 1.2.0 |
| 1.2.1 |
| 2.0.0 |

|===

For each picked version a corresponding playbook content source entry is created which:

* points to a local transient cached on-demand git repository the artifact has been extracted to
* is configured with the same https://docs.antora.org/antora/3.0/playbook/content-source-start-paths/[start path(s)]

== Contributions

xref:CONTRIBUTING.adoc[Are welcome!]
