name: 'Test Report'
on:
  workflow_run:
    workflows: ['PR']                     # runs after CI workflow
    types:
      - completed
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Mocha Tests
          path: 'test-results.json'
          reporter: mocha-json
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pr.yml
          workflow_conclusion: completed
          pr: ${{github.event.pull_request.number}}
      - uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: "test-results/coverage/lcov.info"
          lcov-base: "ref-lcov/lcov.info"
