name: 'Test Report'
on:
  workflow_run:
    workflows: ['PR']                     # runs after CI workflow
    types:
      - completed
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-results
          run-id: ${{ github.event.workflow_run.id }}
      - uses: dorny/test-reporter@v1
        with:
          name: Mocha Tests
          path: 'test-results.json'
          reporter: mocha-json
