name: 'Test Report'
on:
  workflow_run:
    workflows: ['PR']                     # runs after CI workflow
    types:
      - completed
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - uses: actions/download-artifact@v6
        with:
          name: test-results
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: dorny/test-reporter@v2
        with:
          name: Mocha Tests
          path: 'test-results.json'
          reporter: mocha-json
          use-actions-summary: false
